---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: pprv
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - api.pprv.kr
    secretName: tls-certs
  rules:
  - host: api.pprv.kr
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pprv
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: pprv
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: ghcr.io/hellodhlyn/pprv-server:v0.0.1
        name: api
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
        - name: DB_HOST
          value: '10.34.96.3'
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          value: pprv
        - name: DB_USERNAME
          value: pprv_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
        - name: CORS_ALLOWED_ORIGINS
          value: 'http://127.0.0.1:3000,https://pprv.kr'
        ports:
        - containerPort: 8080
          name: api-port
        livenessProbe:
          httpGet:
            path: /ping
            port: api-port
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /ping
            port: api-port
          initialDelaySeconds: 20
