---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  namespace: dodam-io
  labels:
    app: sidekiq
spec:
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - image: ghcr.io/dodam-io/mastodon:v4.0.2-dodam2
          name: sidekiq
          command: ["bash"]
          args: ["-c", "bundle exec sidekiq"]
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 1024Mi
              cpu: 1000m
          envFrom:
            - configMapRef:
                name: mastodon-envs
            - secretRef:
                name: mastodon-secrets
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sidekiq
