---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cms
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - cms.lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: cms.lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: cms
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cms
  namespace: lynlab
  labels:
    app: lynlab
spec:
  type: NodePort
  selector:
    app: cms
  ports:
  - port: 8080
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: lynlab
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - image: ghcr.io/hellodhlyn/shiori:v1.0.1
        name: cms
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
        env:
        - name: RAILS_ENV
          value: production
        - name: SHIORI_DATABASE_HOST
          value: 10.34.96.3
        - name: SHIORI_DATABASE_PORT
          value: '5432'
        - name: SHIORI_DATABASE_USERNAME
          value: lynlab_user
        envFrom:
        - secretRef:
            name: secrets
        ports:
        - containerPort: 3000
          name: cms-port
        livenessProbe:
          httpGet:
            path: /ping
            port: cms-port
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /ping
            port: cms-port
          initialDelaySeconds: 60
