---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wiki
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - wiki.lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: wiki.lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: wiki
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: wiki
  namespace: lynlab
  labels:
    app: lynlab
spec:
  type: NodePort
  selector:
    app: wiki
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: lynlab
  labels:
    app: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - image: hellodhlyn/shiori:v0.1.0
        name: wiki
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
        env:
        - name: DB_HOST
          value: '10.34.96.3'
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          value: wiki
        - name: DB_USERNAME
          value: lynlab_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 8080
          name: wiki-port
