apiVersion: ENC[AES256_GCM,data:9j4=,iv:wL9hnWGhzZRIkp4l4BRKLa1ZV6rg7IK3Jub459mTrho=,tag:KjYEXgGUTwB6ybJZg7ZLQA==,type:str]
kind: ENC[AES256_GCM,data:Yu2x6efp,iv:rolFc2n2F994gcc4pb6Q+DSrR3YEDUa5Bu6tWcKJB48=,tag:k5pvWPJIj8D72GLgYIsFXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+RuNcExQEKWV2L8pB/c=,iv:a6MQRyiSCXDkSKKceg1QoikCX81Hji5nAKcK2It/TEY=,tag:MQM5sEVvJxNL3RhRLX0EXg==,type:str]
    namespace: ENC[AES256_GCM,data:gvAZQpGR,iv:IM6pxOwcTl7vW/f0urbvoSuRWiO8ZD2nJDLtRmbqfWE=,tag:CKny8+j72gAt9gTmv9vUxg==,type:str]
stringData:
    SHIORI_DATABASE_NAME: ENC[AES256_GCM,data:wYNNjkEJrMZWAXbXPQK3nrA=,iv:zAinZR8x0mnwdwf4+F93QGTTGa5xq4dA0lqCkN7PdmI=,tag:DkNZU5C7atz5PoNavgSPzA==,type:str]
    SHIORI_DATABASE_HOST: ENC[AES256_GCM,data:VixfQQMgtJwAEA2lk4i0cVSWRt49VTjDCbHh0Cj8FXINgF36xoVGZBI3GVqUqsFyqVc8nfqPX1jNSaJs++fW05c5ohrJUQH24rJLO9jD6lU8d2piXnGy9zk=,iv:EPZ+NmeijoNgI1ARpDAMYTlLIs+EuZiaFgOSQRWS8LQ=,tag:J0XJnH6Ne12HOYA+aD315A==,type:str]
    SHIORI_DATABASE_PORT: ENC[AES256_GCM,data:nyCzMg==,iv:CclNgh9c3r6KdapbbLFJAH7i5QgHSBLbW4h1vtmkWzk=,tag:Abw/TgNWm5V7OjK4UszM+A==,type:str]
    SHIORI_DATABASE_USERNAME: ENC[AES256_GCM,data:VJJ8LcL9+Rg/wZc=,iv:OxsV0RLaaC9WJu7cKIjeiSNChP8bLeyYdBqkKFgJi6I=,tag:Bz8jJ9CO1H0h/qjmtHR2BA==,type:str]
    SHIORI_DATABASE_PASSWORD: ENC[AES256_GCM,data:N8hgypF04IVW7adO0Jq+r+lwzct9Kffb,iv:GB0bVLrVggUtRCo5Iqhjl7b+CjlD3IwDCJ2VzXbYhDk=,tag:c/n2dR3CbbGuG16JiiYDaA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:YGU5YFTIdKKb8+BEBIEwaQqf5dG2+JsCI0Kszqn5J/5s65hnisCoVAkAagiYFMXe9HA0W3jXYr1Rhx5oo30VgyIrQxVUho39wEnhOIgUFUqfwmFidPjFsOFegtaNnEUHKFoj3v4VzmGs42Mm7IOGBZvFwHxku62jXOAEuB31XTw=,iv:yzxbsGIAjui9ECb2qf4Qez/9CWy3u/hpQU1I+85O9rE=,tag:9UHtVTeldBdUD9o+wsYH4Q==,type:str]
    API_TOKEN_SECRET: ENC[AES256_GCM,data:mlfTQoAsbEPt6TeD2aPUkjClybFuA4JzP9fiob9WyBws9SxiS8uAXW9ddgHjhYzYEeicKaW8qZkhs7Kq9sl3WQ==,iv:TTG0gHQZnRQqedcunsfSK0ivz08EIfOr9KUVsaLOOqI=,tag:BjyIoyrrq9a1vaBF4WIh2w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:HDZx777eE9SOvdb8oBIOu6LNdfj6tHQaHsJf5sbSZqt2jruVF0cUTB0V/aYiBYsTtkysVCOto3/7Q81sbX8W6AOlxEm94MqJug==,iv:w0m2pA2Y+NRhYx5ad0gPzFGPHP4p5wLvaPzAa8UtYFw=,tag:cSGqB1GHVioT1Vfw8FVn6Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vXSalIgYDaikJkJYeCmXM8o2HACLROj5tW28t6mw7rM=,iv:w/5iNaN9N22amTuIUp47ZY6oMuI0RCYB3vnQh7ppIwQ=,tag:FLxJqjAm/3IYkRSILYsuig==,type:str]
    WEBAUTHN_ORIGIN: ENC[AES256_GCM,data:lNweWPTt7Nwf4qxqJ99KAKbV3BA=,iv:OjVV0vE8wSrxPNGC90Wm+cMSY/l1preqs88ftYPCvck=,tag:xYfzIA4yJA4Qeplr6UVc/g==,type:str]
    WEBAUTHN_RP_ID: ENC[AES256_GCM,data:6p/gHVEQbDbbt7ah,iv:ZJNEoT9Obr+7EJ1vrc7RqikNXH9rQeN2f0vTO52V1NE=,tag:cubamta3AZxjSftb+zk9jA==,type:str]
    WEBAUTHN_RP_NAME: ENC[AES256_GCM,data:CFO92WW5rHAitw==,iv:jViZbuT00HPfbNI38GJJbB/+4Z4FYQDEI8FFOCWGXJs=,tag:38PkG7Kgj35xwHwcTwokTQ==,type:str]
    NEW_RELIC_LICENSE_KEY: ENC[AES256_GCM,data:0AakMZ7nAmh5qJ0L3Sc5ftySI/V8GA5cgWRekW2iOrgb/H//smDWuA==,iv:ovPVZcvHcCLZcjiUYgsKFSmlcxu0tFo/LvwShhWwyPg=,tag:kNyBhVUwGgfALtD7ENHrGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df06v56tkw6qdtyde9x9l48d5pnxugcg4khv9wf33qsdj3apqvpsz2kjxv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGJGSFZDMThqL25XZEFM
            MmQzU2NLTU5mYU0wR05LN2x2bVhPRmJYMTIwCnFUNExmUWZTVVhLdnBJQzh5ekp2
            YlU4dXdKbnV5cURoUW9HUmhEL29kVVUKLS0tIFpERnRlcXNCM05iU2locFJ3VURK
            N3kwZjFSSzFnY2hncXRlbHk0WkZMclkK3gB84qghZ2vMpolB2oOugETRfDO/i4Mi
            aLmbzXRswotROEAbvgVmspfcIrHjq0jHMfaPX+XfRjWpB4I5/xiYUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T14:31:42Z"
    mac: ENC[AES256_GCM,data:7tJzoU+f6IOQ2olQ5Z5orAx6xfBKRGYlgyvC4WexkGFzWhztGlpAbNmw/XYeeUlsjalyqCl9u2gZ3OWsSxQuTQ15Emteovc9RrarvX20RyQ6Idk/h4iPiWb1s8S+zCMKJf87whYD98qqAOyW9lldCLgToJ9T37GBL99mIZf2WvA=,iv:6YCM2WTRSJjOtevbabMbPGBSesFm0sunfBhHGXdwQBE=,tag:xSVZ2lOEuZGnKcjpJEqW/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:mEQ=,iv:kGaTBldQzw00y2mqZKMHFpTx2jxaWAGGw4NfwGR5p+o=,tag:+rKyCsGtw29arMkMY2XG7A==,type:str]
kind: ENC[AES256_GCM,data:lSVLGXBH,iv:YLO/JjhhZcekfcRSUnlMQg5HDpWLAsmzVO6rnMz6JNQ=,tag:TJ1tVIToPHtFaVGdftkX4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sBx19v/7sWPlpgjS4yJpww==,iv:PdQDmcsANbzDjz7VEbNOD5Z3b0CiI5czCCDbAKTI8Xc=,tag:TvZ2CibT8Ltdvpv1DEzzMA==,type:str]
    namespace: ENC[AES256_GCM,data:UVUG3KxS,iv:Zzm2fQ/poHASRRey3x7KIjJSwicMHuRKrPM2r5bEEfM=,tag:bQ1aDQYza5TKfpw5Ivm4Gg==,type:str]
stringData:
    tls.crt: ENC[AES256_GCM,data:6ZwyfMiue8cbadbBCyn7ClUPFQFQe2b0+4wARpeCypY+DLuSR1R6RSFdOKZgMgCJCCr7WoMuZadmvfcWU6HXzTYhvrvjRoyr2OqhBmUPswk7vOBHns79zWG6wQL0tccyL5I3eSM3n4J9K/53H5HwsjFYrKlnMeS1n1Wiwa+3NxV6/1C5p3BPdjt//tYnhJm1r/8agL1fbFqxnaC7n2SNS9Lr+s0fMk4PfNxrFgPK3FuIxZs+jpHm68+Nv0qcB31D4qtfFxDvisY0tsWJ5zkcaAQRCdr52X8UVot0StXEbVo04su41bKPMOuJVyt505IRN5z+MIxWLpBQsH1llyk/jMR0vul0mBGEe/B44eqVFveeaa1zbCHKz85aMsycnpZJNjBX4e6XYRppds5SMyRwP81N2I0ajNlEXO5hVHaXDzAusoeOh38/QGgE7xSjpTb5FAihl3zRt38R/C0hg163t3sZS7LpQY0fa+eDDQWSM277pKPro2sGP9imdCzudCgnRswpKpaEjCOziZv1Y9YcgyghxBDBgkxwPNGJG/ojrtiD9Ab/EPCojsdoZmlv/9FVSZa1ssDDEQaQYqB1/V57FhiQTmkh2xMIz+5URsyKMCAw+e8ZqNWEoT4WwOdItFtjeQBW3eidvRC+3IQjz8S8gKDsMxJv5tNVf2AAMn5vcTE6gLpPj7ObySYHbKkB3Y9KHrCkdBguVMVLJLy/KdiWf22oJsLwpl8/JR8XYdck4fYneIiZw8HBD7ySIVxgs1vUsBMtxNgwxK9dPlfJYXX6CJtdVXrgSA9PwuDe+nftO639R3/yWZ0YuNe2XcrYAWjDSN6qRDVCT8YN2PC+jIsPhCSE7wun/0pRCXCiEoHq80jbi1CBBO6K8bYRpgad+1x5uiOBZQk+77AoEJTsihvEl1beM1t0NPMZbQOtjuJZNsYw1zwQCdDDQPssRCgfRM+Q80mraUgJFsj0U5wMFeNZVSh05dIjHf1DNrvwn/Hxt/xHdjCKJtyWqppoat5JnQexBekI+RNU7E5Lw6796Xo11K4xe6gZpJCfhYcKct/NFW3G4uCoTqTMaq1s4SmHtrDaQlCVjrILDWZyqJp1HIRQhc95JpvrpvqlYrVxdXQnNDwQfqIPAK0950gfEAQeCw5njl5GtQiRG4mqQlBSnwwpJTkNT/w6BKGkjxVa+bj6qnbG8Zt44zE2ney9vSpxW7DC7/bMG3r6xbqfOh7zXguqyt1N5n3HeVh6wzuqWA+0gt23cjmacq9yHgaLnLZ4ujr3f3TSn+aOXPtpDzqKUWe+sp8jKh0VzuuNAyeN8r62d1E1y29u9Zokuoq8C3ToVAz/liPHeMTEQhSbmNzcL8uGqxExrxJbhVo5W6N1XXOx9WA2c3naX3FDMoT0TbSRpTDTHaJSUi+o0RMjCnHA3FEnV4+1UV250eZ+zT8Rt22PaIvj/1jOarSMNKzMKUJaYVxAxvVLbI5hWbuVENv+9wYTvl19ckTVc61YtkerXAIOq8OZSSr+c/tdXzZhsHZK9g0=,iv:RQx5jaDE5pSdLA3fKrduJzdn/h0P+rrRpx3cwfwOGFI=,tag:u+vkLUTfkRpmdxteb9yYQw==,type:str]
    tls.key: ENC[AES256_GCM,data:1nNHfwavxBIXhzwQAu4hvM+YWXDbgWC5yPiDxnc4WyQfQv5pEz+N9kU4J05n9tam9X6bOYY+5ZLv5OBBCIc2hTA/5j+q8irHeNPbcre/XRQnLDDMbPa7PivdCfaaphLqS126Z3jxmv1pWZB0GK/gx4zPg0nLm/e1SO8DN9rcVfe92Wyj36mLZ9MTOb+4LVyQyY2adFGq7zO0lvEqbTjWvjPhW0XVXfqc0zfMmRbD2NMOks4s+v/KwxLld55CD/6hErhvlVOPN1eRoTjW7ndbvrk3+cOrEWd4QJPwuYlzjgd/68xOQZBRabBuC0vs53tp8Q==,iv:lmTEtaTFdtRxRrA5j071v5akU0CUC09OaAZcnxbCXdg=,tag:dhgPTKx8LhBHbxqwQBNdKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df06v56tkw6qdtyde9x9l48d5pnxugcg4khv9wf33qsdj3apqvpsz2kjxv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGJGSFZDMThqL25XZEFM
            MmQzU2NLTU5mYU0wR05LN2x2bVhPRmJYMTIwCnFUNExmUWZTVVhLdnBJQzh5ekp2
            YlU4dXdKbnV5cURoUW9HUmhEL29kVVUKLS0tIFpERnRlcXNCM05iU2locFJ3VURK
            N3kwZjFSSzFnY2hncXRlbHk0WkZMclkK3gB84qghZ2vMpolB2oOugETRfDO/i4Mi
            aLmbzXRswotROEAbvgVmspfcIrHjq0jHMfaPX+XfRjWpB4I5/xiYUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T14:31:42Z"
    mac: ENC[AES256_GCM,data:7tJzoU+f6IOQ2olQ5Z5orAx6xfBKRGYlgyvC4WexkGFzWhztGlpAbNmw/XYeeUlsjalyqCl9u2gZ3OWsSxQuTQ15Emteovc9RrarvX20RyQ6Idk/h4iPiWb1s8S+zCMKJf87whYD98qqAOyW9lldCLgToJ9T37GBL99mIZf2WvA=,iv:6YCM2WTRSJjOtevbabMbPGBSesFm0sunfBhHGXdwQBE=,tag:xSVZ2lOEuZGnKcjpJEqW/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
