---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: shiori
  labels:
    app: migration
spec:
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
        - image: ghcr.io/hellodhlyn/shiori:v1.7.0
          name: migration
          command: [ "bundle", "exec", "rails", "db:migrate" ]
          envFrom:
            - configMapRef:
                name: shiori-configs
            - secretRef:
                name: shiori-secrets
      restartPolicy: Never
