---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: baql
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-server
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /up
  targetRef:
    group: ""
    kind: Service
    name: api-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: baql
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: api-server
        image: ghcr.io/hellodhlyn/baql:v0.1.2
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 500Mi
        envFrom:
        - configMapRef:
            name: baql-configs
        - secretRef:
            name: baql-secrets
        ports:
        - containerPort: 3000
          name: api-server-port
        livenessProbe:
          httpGet:
            path: /up
            port: api-server-port
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /up
            port: api-server-port
          initialDelaySeconds: 30
