apiVersion: ENC[AES256_GCM,data:tnQ=,iv:J+kshzzGlFk4afbZ0v9p+PRCe5You5qHKvPvf1u4+mQ=,tag:2PG7cD7BmuTEhwkE4sveKw==,type:str]
kind: ENC[AES256_GCM,data:pOCeY6TE,iv:APlGLsuWaV6aepqFG7byviICnowaVZjcDhfnPAi6Lzc=,tag:muPzzkdxT8vlrJ22CnBk7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0Fo1VCWoRqcuGXfVik4=,iv:49vhL/tCo4Gv4fN4iy3F037Saj/qA2pHCOKBU4X6UPA=,tag:gkGa+AzKuMbEMX+4jO8VXA==,type:str]
    namespace: ENC[AES256_GCM,data:WoGU1Jnn,iv:qznq7RkdvDtL7IuLph2rKZPWtXQezO+cp3Z0Kd5E5Bs=,tag:UlLPkdybTiBQvmXm1xLdww==,type:str]
stringData:
    SHIORI_DATABASE_HOST: ENC[AES256_GCM,data:PTuNIaX/LMDI4Q==,iv:rF/rSkVBgnVAC/NXm856ZDmjl88ElLugel5g5zAzPu4=,tag:FKAYb1/QKhDGTd6K3MnHCQ==,type:str]
    SHIORI_DATABASE_PORT: ENC[AES256_GCM,data:zy0XFw==,iv:aaCkakCdVnX0aUwEjQjaclWpPtw3VfkoOcyBr+dl1HA=,tag:A4LuM9epRNuSzLxDRiTiag==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:PWOXOdk0CBoJNJkxi21qgFlEJZI3eFK5XJ/I4efjOYqaGhXgMm+rvzVDmmNBZDmR5ME0xA//93l1kOpHZRzoq7V37QwxAvufuWhXA+8yB+TnCmIQk9/QckwvXvpMfm3ZIQDxoFSNzu5adh+NROyyPwymELRFI4cMNbk++YU7ZlY=,iv:jDkubuja1qdD513pz4rFdwv8MFJaTcnk1nFUdQbuG4c=,tag:WPirRCJSg6CM8VGbyG0aRQ==,type:str]
    API_TOKEN_SECRET: ENC[AES256_GCM,data:7+A+/RSEHvc01aghGJrU0lHm0niqYTLQ49+uB1aiOfl/TYzWV2e7kvMIo71yvWEgVqxlZqnA1Cy52cvOWWP5Vw==,iv:+E20i83rbUGA71RFy+9tLLD9Ch/Irz+s1GzYz6G5K7U=,tag:GkSzI5nvSPlsERhISh/dIw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:yRNdto6x/ORCyePifE6mlNi75bBMhEx9BbYHMqWT4KOVlGaQPpW5So7+a5gcrvfAs6JS6qgTuIMnmBm1B9MI+hUz5b7ldibA3Q==,iv:wqVkFS9GMkwALCbDOxHUnyau8Lkh2Ukj2d0wz4Y346E=,tag:GAUGwJCIjqK8cofkZUvV0w==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:1GLaNNQ+l7iKJWmjWnRKnc5mEjlE0QXGouSAvIVDdrk=,iv:MvpWsErge8HSHHA3ktPy7vmF/F6K+ZAiBRLiVnC3nAs=,tag:2TVrkB7Wgi8A8TqIPjlT0w==,type:str]
    WEBAUTHN_ORIGIN: ENC[AES256_GCM,data:Rnypww95L6tKBwMHtAFu7LaWSGA=,iv:9oM5qoK+tTnER2P+YCwscXuLugA3k8l1DhcJKhTGIG4=,tag:a2WeXDtNHbrCUIvxRkBOyA==,type:str]
    WEBAUTHN_RP_ID: ENC[AES256_GCM,data:kNzjDtj18h4WCgy+,iv:Hq9gggE0TfgaxFLxuQOvR0c90IsbhFjahytuqffWUy0=,tag:17dYXYF+/AYXkw6KXl1x8w==,type:str]
    WEBAUTHN_RP_NAME: ENC[AES256_GCM,data:F2hCCiro64mNlA==,iv:fGKXbW/2KUdUt7iXjLhKaUygUjDi/HS4XqwxMem/ydU=,tag:ZC4OwPmnQAPoNZrK+zquhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-18T17:51:01Z"
    mac: ENC[AES256_GCM,data:MgM6/sxd/pMixRJGxD87G/yTgDDM9rLX3Fvsee7w5yvwzqe7TN4F8//SqTtaAcl/18Wdhzv9ywPg08zD5B0hcS+eC0Vfc/zSn2piMbbIhLROa7cmD1TfsETmI1/qNoHCf8IkBSjIRdpKdHTvQXJ5dDJyWJaNIBxnEGG74tl5+f4=,iv:BJo8lzRZGnKQfrB8hWFo2GhkdFLsu3MBuH8jnVpJghU=,tag:5zg8YSsqGUJaplIuthItUQ==,type:str]
    pgp:
        - created_at: "2023-02-18T17:50:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yPlFtVebfYARAAmHBplJ6VX5qjNGGT3rSsSZ9l3S4OgbzBb/COS4e+500+
            iu8UdzbAsaBAeba8qTW4Se9VixT7T95njaIjxGZcSCzRkAvyL1fAeP35o/eg9ldH
            L4rTdN5UGiw5MG4ihkqR6Xt8h0a5UrsElqvlbJvM1ehHS2lzyZM/IIRqDFyWeyDm
            xM8NZxihAgyPWYEJ/qiaznLOWp0g977yGCQ0xlkWw6p811M3wE+12qHRZedtqYSa
            wqkLgleMVuV+nx6xMUnLwejxHMEc755fqdaBd/Ox2cBRugwlAh7vFGrsIgMrRdbv
            JS0j9lCbdbgAqRJW1Si+BcUHBmucYePgDnVOmnGjj5pPdt5WQ4iYglcOVCJil8Fg
            O4nDG9p8sBqc1Ggp8cSARUU7humcXFWQ/fgKDF9TqV/fHucVhgsc+8LTReIv1vs9
            6vBB+0mjAZShr985PEY7LRuGV+IyMEfH7wwBVxEGcwbHF+kCAZgECPDV2Sc2l15p
            WrpYOwttUEElYp1QGfjkwFM62qPM88+uYxt4vaectZbdc2Tw0LiLduHqN9I9v3PU
            m96GkgHdooxZes/Uv8BosgjkzWM6no5BMCD6Z/RX01+hu0dr/cw7RtZDYwa83d3g
            /qCD0kJmwRegU+yhAl6nltujhMhkip0Cbni9E4zP4k3MOcgC6q++57AAxmHIfQnS
            UQHCqlP3sIYd139k8jl0AaBeVrkFFK5BV2UKEVYiOsSzVHvtf34I4esk/uhyW8zo
            LFLqq2jyYz2+iQuqAKkd0f6No7FIEJUzVXGjD/56jdpvfQ==
            =Ln+x
            -----END PGP MESSAGE-----
          fp: 1d1a32d148edf1e8a536f7a08a82a50a2df52ee4
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:KOw=,iv:5mM9S+b8Rr1OMB1MdmFy2gRNjr8g2EGLL4xy1n4QnAU=,tag:EJDODmc1sjPrMFKLPJIs0g==,type:str]
kind: ENC[AES256_GCM,data:5xNNB4Mh,iv:oaqoJiVAi6D5v9Nw+o+28l1la+DW2G//lZ1eRzQTTkA=,tag:3CmL18b2w6+676/q6qwYXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w9fQhFj+DDeTc4jdTfEVet7dMnoB3dSf,iv:XWtCG2GcV02TF+QOqtDBlW7A0ydqXBItyRXewFu1Yc4=,tag:O0s9DB5TZHcTIWLJrHKSxw==,type:str]
    namespace: ENC[AES256_GCM,data:qqz0BWjk,iv:fLduyJi3KVdWASV1WCCHlrk6LS/itbBU+5MjtPfYCMQ=,tag:KkX76dWSZTMYwGJklEzOYw==,type:str]
stringData:
    SHIORI_DATABASE_USERNAME: ENC[AES256_GCM,data:+yjltverJ78=,iv:hRntedpCl/I8pHXDYOD0GqOD912xAUjC5PN3e5UB3hg=,tag:03VE0dWShMk8XhFDsi3PJA==,type:str]
    SHIORI_DATABASE_PASSWORD: ENC[AES256_GCM,data:3kfT/gDdDQK3lkcVeSt4WybWC4V3ZD9MGSb9P8UnB4Y=,iv:4TltOgYCKvHaNqr9a122K6/INU9Uf03iUBBZo68mt0c=,tag:/Wulfenb3e66PchahsR3HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-18T17:51:01Z"
    mac: ENC[AES256_GCM,data:MgM6/sxd/pMixRJGxD87G/yTgDDM9rLX3Fvsee7w5yvwzqe7TN4F8//SqTtaAcl/18Wdhzv9ywPg08zD5B0hcS+eC0Vfc/zSn2piMbbIhLROa7cmD1TfsETmI1/qNoHCf8IkBSjIRdpKdHTvQXJ5dDJyWJaNIBxnEGG74tl5+f4=,iv:BJo8lzRZGnKQfrB8hWFo2GhkdFLsu3MBuH8jnVpJghU=,tag:5zg8YSsqGUJaplIuthItUQ==,type:str]
    pgp:
        - created_at: "2023-02-18T17:50:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yPlFtVebfYARAAmHBplJ6VX5qjNGGT3rSsSZ9l3S4OgbzBb/COS4e+500+
            iu8UdzbAsaBAeba8qTW4Se9VixT7T95njaIjxGZcSCzRkAvyL1fAeP35o/eg9ldH
            L4rTdN5UGiw5MG4ihkqR6Xt8h0a5UrsElqvlbJvM1ehHS2lzyZM/IIRqDFyWeyDm
            xM8NZxihAgyPWYEJ/qiaznLOWp0g977yGCQ0xlkWw6p811M3wE+12qHRZedtqYSa
            wqkLgleMVuV+nx6xMUnLwejxHMEc755fqdaBd/Ox2cBRugwlAh7vFGrsIgMrRdbv
            JS0j9lCbdbgAqRJW1Si+BcUHBmucYePgDnVOmnGjj5pPdt5WQ4iYglcOVCJil8Fg
            O4nDG9p8sBqc1Ggp8cSARUU7humcXFWQ/fgKDF9TqV/fHucVhgsc+8LTReIv1vs9
            6vBB+0mjAZShr985PEY7LRuGV+IyMEfH7wwBVxEGcwbHF+kCAZgECPDV2Sc2l15p
            WrpYOwttUEElYp1QGfjkwFM62qPM88+uYxt4vaectZbdc2Tw0LiLduHqN9I9v3PU
            m96GkgHdooxZes/Uv8BosgjkzWM6no5BMCD6Z/RX01+hu0dr/cw7RtZDYwa83d3g
            /qCD0kJmwRegU+yhAl6nltujhMhkip0Cbni9E4zP4k3MOcgC6q++57AAxmHIfQnS
            UQHCqlP3sIYd139k8jl0AaBeVrkFFK5BV2UKEVYiOsSzVHvtf34I4esk/uhyW8zo
            LFLqq2jyYz2+iQuqAKkd0f6No7FIEJUzVXGjD/56jdpvfQ==
            =Ln+x
            -----END PGP MESSAGE-----
          fp: 1d1a32d148edf1e8a536f7a08a82a50a2df52ee4
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:3tk=,iv:T+wC1vdATmXkt+9yHDlRS7zpojNSfV8zf+kNKv0ySOQ=,tag:D+TM7OOOv/22nQp/pTMEmg==,type:str]
kind: ENC[AES256_GCM,data:BszBTZ/q,iv:4Md0HuG+OdByoS6PjT6jOKUKxlKIeQcz9H8J8ZdjPfs=,tag:obZSNswPRBna6a24IfZXbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k6e5ghGXwL2owLxOxDEeVdQtF1lDZwEbNoBtsWPd,iv:zE6T4c1cs8QfeA9IigwP0bJtmY/1GcldjsTOWr/T/R0=,tag:XlpKOvOFPva8TD9pxBi2AA==,type:str]
    namespace: ENC[AES256_GCM,data:9H74Hp46,iv:Gw7z9stSLNrIkk9EYkEuBUY1BE4jOL7LFstOAIfwRPQ=,tag:KlakKi0BERw2kUpdoYv66A==,type:str]
stringData:
    SHIORI_DATABASE_USERNAME: ENC[AES256_GCM,data:LT5hbNebbf4yLsc=,iv:so7wXCf3rKNFruz/gnwpGRkiAYOz/Ns90VxsECf7F70=,tag:NtpQspG5kox13Ta5rxeuVA==,type:str]
    SHIORI_DATABASE_PASSWORD: ENC[AES256_GCM,data:8W0/sjKTs9E5lUzb/Dm3p61N2AQ=,iv:n5DyixLuyBA9NJGGClAZHKDVTmaIGF0EwS37WsDv7Wo=,tag:koBByTLLqIZuGgEGNZbmQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-18T17:51:01Z"
    mac: ENC[AES256_GCM,data:MgM6/sxd/pMixRJGxD87G/yTgDDM9rLX3Fvsee7w5yvwzqe7TN4F8//SqTtaAcl/18Wdhzv9ywPg08zD5B0hcS+eC0Vfc/zSn2piMbbIhLROa7cmD1TfsETmI1/qNoHCf8IkBSjIRdpKdHTvQXJ5dDJyWJaNIBxnEGG74tl5+f4=,iv:BJo8lzRZGnKQfrB8hWFo2GhkdFLsu3MBuH8jnVpJghU=,tag:5zg8YSsqGUJaplIuthItUQ==,type:str]
    pgp:
        - created_at: "2023-02-18T17:50:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yPlFtVebfYARAAmHBplJ6VX5qjNGGT3rSsSZ9l3S4OgbzBb/COS4e+500+
            iu8UdzbAsaBAeba8qTW4Se9VixT7T95njaIjxGZcSCzRkAvyL1fAeP35o/eg9ldH
            L4rTdN5UGiw5MG4ihkqR6Xt8h0a5UrsElqvlbJvM1ehHS2lzyZM/IIRqDFyWeyDm
            xM8NZxihAgyPWYEJ/qiaznLOWp0g977yGCQ0xlkWw6p811M3wE+12qHRZedtqYSa
            wqkLgleMVuV+nx6xMUnLwejxHMEc755fqdaBd/Ox2cBRugwlAh7vFGrsIgMrRdbv
            JS0j9lCbdbgAqRJW1Si+BcUHBmucYePgDnVOmnGjj5pPdt5WQ4iYglcOVCJil8Fg
            O4nDG9p8sBqc1Ggp8cSARUU7humcXFWQ/fgKDF9TqV/fHucVhgsc+8LTReIv1vs9
            6vBB+0mjAZShr985PEY7LRuGV+IyMEfH7wwBVxEGcwbHF+kCAZgECPDV2Sc2l15p
            WrpYOwttUEElYp1QGfjkwFM62qPM88+uYxt4vaectZbdc2Tw0LiLduHqN9I9v3PU
            m96GkgHdooxZes/Uv8BosgjkzWM6no5BMCD6Z/RX01+hu0dr/cw7RtZDYwa83d3g
            /qCD0kJmwRegU+yhAl6nltujhMhkip0Cbni9E4zP4k3MOcgC6q++57AAxmHIfQnS
            UQHCqlP3sIYd139k8jl0AaBeVrkFFK5BV2UKEVYiOsSzVHvtf34I4esk/uhyW8zo
            LFLqq2jyYz2+iQuqAKkd0f6No7FIEJUzVXGjD/56jdpvfQ==
            =Ln+x
            -----END PGP MESSAGE-----
          fp: 1d1a32d148edf1e8a536f7a08a82a50a2df52ee4
    unencrypted_suffix: _unencrypted
    version: 3.7.3
