---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: shiori
  labels:
    app: migration
spec:
  template:
    metadata:
      labels:
        app: migration
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - image: ghcr.io/hellodhlyn/shiori:v1.3.0
          name: migration
          command: [ "bundle", "exec", "rails", "db:migrate" ]
          env:
            - name: RAILS_ENV
              value: production
          envFrom:
            - secretRef:
                name: shiori-secrets
            - secretRef:
                name: shiori-admin-credentials
      restartPolicy: Never
