---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: undersky
spec:
  template:
    spec:
      containers:
      - name: undersky-migrate
        image: hellodhlyn/undersky-migrate
        command: [ "./migrate", "up" ]
        env:
        env:
        - name: DB_HOST
          value: postgres.lynlab
        - name: DB_USERNAME
          value: undersky_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: undersky
              key: POSTGRES_UNDERSKY_PASSWORD
        - name: DB_NAME
          value: undersky
      restartPolicy: Never
  backoffLimit: 2
