---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: undersky
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: undersky
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: hellodhlyn/undersky-api
        name: api
        env:
        - name: DB_HOST
          value: postgres.lynlab
        - name: DB_USERNAME
          value: undersky_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: undersky
              key: POSTGRES_UNDERSKY_PASSWORD
        - name: DB_NAME
          value: undersky
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: undersky
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: undersky
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 8000
          name: api-port
