---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: luppiter
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - auth.luppiter.dev
    secretName: tls-certs
  rules:
  - host: auth.luppiter.dev
    http:
      paths:
      - backend:
          serviceName: auth
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: luppiter
  labels:
    name: auth
spec:
  type: NodePort
  selector:
    name: auth
  ports:
  - port: 8080
    targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: luppiter
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - image: hellodhlyn/luppiter-auth:v0.1.3
        name: auth
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
        - name: DB_HOST
          value: postgres.lynlab
        - name: DB_USERNAME
          value: luppiter_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DB_PASSWORD
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: SECRET_KEY_BASE
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /home/app/config/service_account.json
        ports:
        - containerPort: 4000
          name: auth-port
        livenessProbe:
          httpGet:
            path: /ping
            port: auth-port
          initialDelaySeconds: 120
        readinessProbe:
          httpGet:
            path: /ping
            port: auth-port
          initialDelaySeconds: 120
        volumeMounts:
        - name: config
          mountPath: /home/app/config
      volumes:
      - name: config
        configMap:
          name: google-config
