---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdo-bot
  namespace: webdonalds
  labels:
    app: webdo-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdo-bot
  template:
    metadata:
      labels:
        app: webdo-bot
    spec:
      containers:
      - image: webdonalds/discord-bot:v0.3.0
        name: webdo-bot
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
        - name: BREAKING_NEWS_CHANNEL_ID
          value: '736110542715879487'
        envFrom:
        - secretRef:
            name: webdo-bot-secret
