---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - auth.lynlab.co.kr
      secretName: tls-certs
  rules:
    - host: auth.lynlab.co.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: lynlab
  labels:
    name: auth
spec:
  type: NodePort
  selector:
    name: auth
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: lynlab
  labels:
    name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - image: ghcr.io/hellodhlyn/lynlab-auth:v1.2.0
          name: auth
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          env:
            - name: REDIS_ENDPOINT
              value: vt-db01.vke-seoul.lynlab.co.kr:6379
            - name: RELYING_PARTY_ID
              value: lynlab.co.kr
            - name: RELYING_PARTY_ORIGIN
              value: https://lynlab.co.kr
          envFrom:
            - secretRef:
                name: auth-secrets
          ports:
            - containerPort: 8080
              name: auth-port
          readinessProbe:
            httpGet:
              path: /ping
              port: auth-port
          livenessProbe:
            httpGet:
              path: /ping
              port: auth-port
