---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - auth.lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: auth.lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: auth
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: lynlab
  labels:
    app: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - port: 8080
    targetPort: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: lynlab
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: lynlab/auth:v2.0.1
          name: auth
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 100m
          env:
            - name: DB_HOST
              value: postgres.lynlab
            - name: DB_USERNAME
              value: lynlab_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_LYNLAB_PASSWORD
            - name: DB_NAME
              value: lynlab_auth
            - name: DB_PORT
              value: '5432'
            - name: LYNLAB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LYNLAB_SECRET_KEY
          ports:
            - containerPort: 1323
              name: auth-port
