---
apiVersion: v1
kind: Service
metadata:
  name: lynlab-web
  namespace: lynlab
  labels:
    app: lynlab-web
spec:
  type: NodePort
  selector:
    app: lynlab-web
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynlab-web
  namespace: lynlab
  labels:
    app: lynlab-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynlab-web
  template:
    metadata:
      labels:
        app: lynlab-web
    spec:
      containers:
        - image: lynlab/lynlab-web:v1.3.0
          name: lynlab-web
          ports:
            - containerPort: 1323
              name: lynlab-web-port
