---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lynlab
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lynlab
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: lynlab/lynlab-web:v1.6.1
        name: lynlab-web
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 8080
          name: web-port
