---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elysia
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - elysia.lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: elysia.lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: elysia
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: elysia
  namespace: lynlab
  labels:
    name: elysia
spec:
  type: NodePort
  selector:
    name: elysia
  ports:
  - port: 8080
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elysia
  namespace: lynlab
  labels:
    name: elysia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elysia
  template:
    metadata:
      labels:
        name: elysia
    spec:
      containers:
      - image: hellodhlyn/elysia:v0.1.2
        name: elysia
        resources:
          requests:
            memory: 150Mi
            cpu: 100m
          limits:
            memory: 150Mi
            cpu: 100m
        env:
          - name: ELYSIA_CORS_ORIGIN
            value: https://lynlab.co.kr
        ports:
          - containerPort: 3000
            name: elysia-port
        livenessProbe:
          httpGet:
            path: /ping
            port: elysia-port
