---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bridge
  namespace: lynlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - bridge.lynlab.co.kr
    secretName: tls-certs
  rules:
  - host: bridge.lynlab.co.kr
    http:
      paths:
      - backend:
          serviceName: bridge
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bridge
  namespace: lynlab
  labels:
    app: bridge
spec:
  type: NodePort
  selector:
    app: bridge
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: lynlab
  labels:
    app: bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
      - image: hellodhlyn/webhook-bridge:v0.1.0
        name: bridge
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        ports:
        - containerPort: 8080
          name: bridge-port
        env:
        - name: BRIDGE_CONFIG_PATH
          value: /etc/bridge/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/bridge
      volumes:
      - name: config
        configMap:
          name: bridge-config
