apiVersion: ENC[AES256_GCM,data:bNk=,iv:PYGlk5WuaMq+js4qQcyjmXwAKpaVUIEh6VhGbFDCa4s=,tag:SjDh+lbS+EqCvT1GLA43Yg==,type:str]
kind: ENC[AES256_GCM,data:IcA0b95l,iv:+ZLO9lrlxKgQO8QnVgKu9BcYndgnT3CztnINC9ZqKps=,tag:sFIOvSXxe+JLuY4e82UNuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ftyc2ghAd3rdeai4ph6erw==,iv:f8xFKmPYuHNDCHGj6/nOtrlvrraWKt70nuHagMUPo2Q=,tag:4JcI0myCu8ywyGIViqY6pw==,type:str]
    namespace: ENC[AES256_GCM,data:tm8ex6n0Vw==,iv:iyOuf9j7zkSUViZkVQ0meNZO9lIJNRX8sh9tD32Dm8E=,tag:AUY1G6YU13QC8Yy+CYYfgg==,type:str]
type: ENC[AES256_GCM,data:Zb6d+j/Q,iv:oEeN4mWHiT2ilChrqRdnQ6fprl4bmn41Xy/B7/utTs0=,tag:jUSFP8qIm7bQlGK1+jNzWg==,type:str]
stringData:
    pgbouncer.ini: ENC[AES256_GCM,data:dBfSdjeKvDYfY3esHOJR1EzWc0jeSi5c1bEciN16Zk4HMkkqnEIa1cr7nusK02qktOer70AiSMQATf6p7oTLUjIBaRiJA+Dmq53C0orqQhRYzYClEiHsSDu9B7rSiPs7xmPX7+9/h1aNISH3WmZePuUXbriaqLG8foAvTnizrSNqLQOIawHljSKcGbWINQ9sxgsZFBd24V5FZtdpIJoiDlOCkglZqi66DE07dAkFkYnxr7R0B7C3Peqaaf7zNTB/jeWIwX6r4T7z/ATzFUEr2/fK5oKOxBaX9AHAM19eiA4XmX+nJy65jcBW27k90P581e9OYyfZqDf1br2HzvMzSQcbd4tLaRPSmLjFgfUX5/14phvFQhtauNN5TsNPJkmhbaNoGhhm8VCRNBH+cgjObK+D7LjvYuR6e+L3Hv+H8CgQH8BtxGXdPENQM7G4NlQdvUiWq3E8WQXV/+QEVXnQ8BHFMR1hk6BKsP4p3jNwofqXoXKwENKIQ3X10NwQVCxUzAMhvR2bwiY0QLqhMv3lZChqzxsEvvUDhHdhbPPdt5qvEa224NPBdZHx1IJCDgzwvzquT+S4mYgk0Q54Yv79Eyrcek06B2B072sDwjb81UtVcHhf+Hh1jZ20lIRiP45VvVPgqsWuknTfIp5NJ7zIlOs2gw==,iv:uMXhFmp/7w1o9pIC30ss/h25FKKtdMZQAq/TBYGl44w=,tag:mgszrZX+Uok7RWnxZxsDPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df06v56tkw6qdtyde9x9l48d5pnxugcg4khv9wf33qsdj3apqvpsz2kjxv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVVsb2J4NnhxK1pkWEpx
            Mm5GMkxEU1NQODJERGZBNmlrV2VMd1ZtckhRCjkxbkVCR0o2akUvLzZuVFdSVVhE
            bUk3NHdKZWNPazdWZnhaY2hTb3J3L2cKLS0tIC8rNGVaN2MweGc3NWRyUWhNbGY1
            QXZSbmhEY1lra2JOOEpROFZYVE9ZeUEKStoX/o7XVa3f3E76EIzVZHEnpTyUv+1B
            paGvX/GNTRDikEFT1bjeOidm+PSr6Ko0HOX8PhsRvnkJcuvDscy+vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T16:33:13Z"
    mac: ENC[AES256_GCM,data:hn+k+KA/hBGFJogXNnE/iW+J19KIr6ykeVdXtiu1S1pwQ6NhEhCxVhG+mamtNOvIde1KFfP2S7+qkiZR47kM6qyUgV4pXkhBaMIqt2fAvgWttz7vPG5uB3Ww9zW4O5XjLSZ8nAe1f/mzRfx2+l4eihbgz25k2zogEAyY/LvR3eY=,iv:3AbgEs4KT4zY9T7Oe1EJbGSxdSYObi+LUdI2MjkryPk=,tag:y94Fa6iGch44kh693IdVfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:w1k=,iv:YM1TwEJUYh0MRNwwp7GWMk8IlkECZ9BZ0Dv4kDs9RO0=,tag:8oyqKOk4G4aMRCeklNPRMQ==,type:str]
kind: ENC[AES256_GCM,data:RlzmxAjR,iv:L6NBOb9dCsP25sX3J7aE81uEVmQORHF9oaaIPuKXRIE=,tag:C3uvYexP4idGmRloWxXXaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r+rrcN9U68bJ/tuaVNZ2Bg==,iv:EphpdmO8TLP6V1hQj/bOlevDRgiNlzmY+uSpXEVaLnI=,tag:yBsXP8E/MwR4EtmdFQ2Tfw==,type:str]
    namespace: ENC[AES256_GCM,data:l7QZqw8zYQ==,iv:CCKSneutCyzDJuHBOWnWygG+nRcz9UHvdRlCPgKaEGI=,tag:IbQFJb/UDsCQPfoe6GHEdw==,type:str]
type: ENC[AES256_GCM,data:HEl3fClD,iv:Mn2cB/dk4JMqRHct6AnkobsB960nOy9OEW1iwMklLGI=,tag:Ige2IHx1nM+M22dk/v/OTQ==,type:str]
stringData:
    userlist.txt: ENC[AES256_GCM,data:4dEcqMcA25Y6lkg1EclkqCmKIIfcJGq2Xb/lec0qh+rD5HyG0FyVPCPFwG8nx1ljYZZi7scQ4gTWKS6+CPh6/gR3xxW+A6/7KoeT8rbACewJOA5fSShaQ2WH9K9LVM3Gk/itBOwXoY1gJcwmUO27hHzfm+QYCiA2,iv:RpHIrKrTqe1X9cbwHJ3xUYhV5wrC6er5PCVTfG9A5Gk=,tag:+eYSbHhEYFe2aH7rCGOF8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1df06v56tkw6qdtyde9x9l48d5pnxugcg4khv9wf33qsdj3apqvpsz2kjxv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVVsb2J4NnhxK1pkWEpx
            Mm5GMkxEU1NQODJERGZBNmlrV2VMd1ZtckhRCjkxbkVCR0o2akUvLzZuVFdSVVhE
            bUk3NHdKZWNPazdWZnhaY2hTb3J3L2cKLS0tIC8rNGVaN2MweGc3NWRyUWhNbGY1
            QXZSbmhEY1lra2JOOEpROFZYVE9ZeUEKStoX/o7XVa3f3E76EIzVZHEnpTyUv+1B
            paGvX/GNTRDikEFT1bjeOidm+PSr6Ko0HOX8PhsRvnkJcuvDscy+vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T16:33:13Z"
    mac: ENC[AES256_GCM,data:hn+k+KA/hBGFJogXNnE/iW+J19KIr6ykeVdXtiu1S1pwQ6NhEhCxVhG+mamtNOvIde1KFfP2S7+qkiZR47kM6qyUgV4pXkhBaMIqt2fAvgWttz7vPG5uB3Ww9zW4O5XjLSZ8nAe1f/mzRfx2+l4eihbgz25k2zogEAyY/LvR3eY=,iv:3AbgEs4KT4zY9T7Oe1EJbGSxdSYObi+LUdI2MjkryPk=,tag:y94Fa6iGch44kh693IdVfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
