---
apiVersion: v1
kind: Service
metadata:
  name: hollo
  namespace: wolzip
  labels:
    app: hollo
spec:
  type: NodePort
  selector:
    app: hollo
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hollo
  namespace: wolzip
  labels:
    app: hollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hollo
  template:
    metadata:
      labels:
        app: hollo
    spec:
      containers:
        - name: hollo
          image: ghcr.io/fedify-dev/hollo:0.6.0
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: hollo-secret
          # ports:
          #   - containerPort: 3000
          #     name: api-server-port
          # livenessProbe:
          #   httpGet:
          #     path: /up
          #     port: api-server-port
          #   initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /up
          #     port: api-server-port
          #   initialDelaySeconds: 30
